config/routes.rb
Rails.application.routes.draw do
  resources :links
  
  root :to => 'links#index'
  
  get '/:token', to: 'links#destination', as: :tiny
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hit.rb
class Hit < ApplicationRecord
    belongs_to :link
    
    validates_presence_of :address
end

app/models/link.rb
class Link < ApplicationRecord
    has_many :hits, dependent: :delete_all
    validates_presence_of :destination
    validates_uniqueness_of :destination
    
    # There could be HEAVY optimization here by caching the 
    # token -> destination into memcache or redis.  This is 
    # very easy in this case as you can write on change and 
    # then let a TTL, or just cache size, expire the unused
    # content.
    
    def token
        self.class.id_to_token self.id
    end
    
    def token_url
        Rails.application.routes.url_helpers.tiny_url(token: self.token, only_path: true)
    end
    
    # This is a simple transform to make the obfucated external
    # ID.  Depending on non-functional requirements this could be
    # an encrypted, hashed, or some other form of external identifier.
    
    ID_OFFSET = 1212 # Just to move the numbers up a little.
    def self.id_to_token(plain)
        (plain + ID_OFFSET).to_s 36
    end
    
    def self.token_to_id(base36)
        (base36.to_i(36)) - ID_OFFSET
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show edit update destroy]
  
  def destination
    link_id = Link.token_to_id params[:token]
    @link = Link.find_by_id link_id
    if @link.nil?
      head :not_found, content_type: "text/html"
    else
      @hit = Hit.create link: @link, address: request.remote_ip
      redirect_to @link.destination
    end
  end

  def show
    @hits = @link.hits
  end
  
  
  ##  BOILER PLATE BELOW HERE!

  def index
    @links = Link.all
  end

  def edit
  end

  def new
    @link = Link.new
  end
  
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private
  
  def set_link
    @link = Link.find params[:id]
  end
  
  def link_params
    params.require(:link).permit(:destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorten</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_area :destination %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Nothing</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tiny TinyUrl Project</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Token</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.destination, link.destination %></td>
        <td><%= link_to link.token, link.token %></td>
        <td><%= link.hits.count %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Destination:</strong>
  <%= @link.destination %>
</p>

<p>
  <strong>Token:</strong>
  <%= @link.token %>
</p>

<p>
  <strong>Count:</strong>
  <%= @hits.count %>
</p>

<table>
  <thead>
    <tr>
      <th>IP Addresses</th>
    </tr>
  </thead>
  
  <tbody>
    <% @hits.each do |hit| %>
    <tr>
      <td><%= hit.address.to_string %></td>
    </tr>  
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>